added __version__ to init to display version of the python package
girder/django-s3-file-field pull request #119
Opened 2020-10-22 20:06 UTC by kushagra219

this is a part of my hacktoberfest2020 goals. Please review and see if it's okay.

2020-10-22 22:32 UTC, banesullivan reviewed
thanks for addressing #104, @kushagra219

2020-10-22 22:32 UTC, banesullivan commented on s3_file_field/version.py
> +__version__ = "0.0.13"
```suggestion
__version__ = "0.0.14"
```

2020-10-22 22:32 UTC, banesullivan commented on s3_file_field/__init__.py
> +__version__ = version["__version__"]
Why this approach and not?:

```py
from .version import __version__
```

----

Also, using `exec` in the package is frowned upon

2020-10-22 22:32 UTC, banesullivan commented on setup.py
> +
Okay to use `exec` here, I suppose

2020-10-22 22:51 UTC, brianhelba requested changes
Thanks for the contribution. I see a few significant issues so far:
* We use `setuptools-scm` to dynamically look up the version from the most recent Git tag. This means that hardcoded version numbers should not be committed anywhere in the codebase.
  * The use of `version='0.0.3'` is indeed a bug, and if you submit a PR just removing that, I'd accept it. :smile: 
* Using `exec` in almost any context is scary. I don't think it's worth using here.
  * I assume you're following (3) from [Single-sourcing the package version](https://packaging.python.org/guides/single-sourcing-package-version/). I suspect a fully working solution might require using `importlib.metadata` from (5).

2020-10-23 06:37 UTC, kushagra219 commented
@brianhelba I have tried to make the requested changes using importlib.metadata as suggested by you and removed exec.

2020-11-05 22:32 UTC, kushagra219 commented
@brianhelba @banesullivan @jbeezley @jeffbaumes sir, it would be a great help if you could just add the label of **`hacktoberfest-accepted`** to this PR.

2020-11-07 05:03 UTC, brianhelba requested changes
@kushagra219 Thanks for the updates. There are still a few issues with this PR, which I've left comments about inline.

2020-11-07 05:03 UTC, brianhelba commented on setup.py
> +version = get_version('s3_file_field')
This entire code block will be non-functional. The `version` being passed here is ignored. The option `use_scm_version` overwrites the version dynamically.

2020-11-07 05:05 UTC, brianhelba commented
@kushagra219 If you're looking for an easy PR to have accepted for Hacktoberfest, just update this PR to *only* remove the line
```python
version='0.0.3',
```
from `setup.py`. That will improve this code by fixing a source of confusion (since the `version` there is not really used), and since you found the bug, you deserve full credit for the fix.

I will happily approve and merge that change.

2020-11-07 15:56 UTC, kushagra219 commented
@brianhelba Sir, I have removed that version line from `setup.py` as you said and removed all other changes. Please see to it.

2020-11-07 15:58 UTC, kushagra219 commented on s3_file_field/__init__.py
> +assert metadata.version('django-s3-file-field') == '0.0.14'
ok got it!

2020-11-07 16:01 UTC, kushagra219 commented on s3_file_field/__init__.py
> +    import importlib_metadata as metadata
It has come from the point (5) of [Single-sourcing the package version](https://packaging.python.org/guides/single-sourcing-package-version/) as you mentioned to do in the above comment.

2020-11-12 00:31 UTC, brianhelba approved these changes
Thanks for the improvement. I'd agree this helps remove confusion.

2020-11-12 00:31 UTC, merged