Add progress reporting to the TS client
girder/django-s3-file-field pull request #147
Opened 2020-12-07 17:29 UTC by brianhelba

2020-12-07 17:29 UTC, brianhelba commented
@zachmullen @dchiquit This is an alternative to #134, which should be safe for use with parallel uploads.

2020-12-07 17:34 UTC, brianhelba commented on django-s3-file-field-client/src/client.ts
> +    protected readonly baseUrl: string,
Note this TypeScript feature for declaring and initializing member variables in one line. I've updated `baseUrl` to do that.

2020-12-07 17:36 UTC, zachmullen requested changes

2020-12-07 17:36 UTC, zachmullen commented on django-s3-file-field-client/src/client.ts
> +  private readonly overheadProportion = 0.20;
I'm not fond of this statically fixed overhead proportion. If we insist on not using indeterminate progress, let's at least base the proportion intelligently on the file's size.

2020-12-07 17:36 UTC, zachmullen commented on django-s3-file-field-client/src/client.ts
> +  readonly percentage: number;
This value ranges `[0, 1]`, not `[0, 100]`, right? In that case, percentage is the wrong name. Maybe `fraction`, `proportion`, `ratio`... some other synonym?

2020-12-07 17:36 UTC, zachmullen commented on django-s3-file-field-client/src/client.ts
> +    this.mainPercentageSegments = new Array(segments).fill(0);
I wrote up (but haven't yet tested) an alternative implementation that uses less memory. It leverages closures to track the progress incrementally:

```javascript
protected async uploadPart(chunk: ArrayBuffer, part: PartInfo, incrementProgress: Function): Promise<UploadedPart> {
    let lastLoaded = 0;
    const response = await axios.put(part.upload_url, chunk, {
      onUploadProgress: (e) => {
        const increment: number = e.loaded - lastLoaded;
        lastLoaded = e.loaded;
        incrementProgress(increment);
      },
    });
    const etag = response.headers.etag;
    return {
      part_number: part.part_number,
      size: part.size,
      etag,
    };
  }
```

...

```javascript
protected async uploadParts(file: File, parts: PartInfo[]): Promise<UploadedPart[]> {
    const buffer = await file.arrayBuffer();
    // indices track where in the buffer each part begins
    let index = 0;
    const indices: number[] = [];
    for (const part of parts) {
      indices.push(index);
      index += part.size;
    }

    let totalLoaded = 0;
    const incrementProgress = (increment: number) => {
      totalLoaded += increment;
      this.progressCallback({
        loaded: totalLoaded,
        total: file.size,
        lengthComputable: true,
      });
    };

    // upload each part of the buffer in parallel using the calculated indices
    return await Promise.all(parts.map(async (part, i) => {
      const chunk = buffer.slice(indices[i], indices[i] + part.size);
      return await this.uploadPart(chunk, part, incrementProgress);
    }));
  }
```

What do you think?

2021-01-17 03:56 UTC, brianhelba commented
Superseded by #164.

2021-01-17 03:56 UTC, closed without merging